#!/usr/bin/env bash

export CONTECO_LABEL="metricbeat.overlay - ConteEco"
export CONTECO_DESCRIPTION="The ElasticSearch Metricbeat base image configured for service monitoring."

export CONTECO_TYPE="metricbeat"
export CONTECO_NAME="overlay"
export CONTECO_TAG="7.1.1"

export CONTECO_BASE="metricbeat.base"
export CONTECO_BUILD="image"
