---
version: '3'
services:

# START SERVICE metricbeat.overlay
  metricbeat:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM}/${CONTECO_ECOSYSTEM}.metricbeat.overlay:7.1.1
    environment: [${CONTECO_DC_OVERLAY_METRICS_ENVIRONMENT}]
    command: [${CONTECO_DC_OVERLAY_METRICS_COMMAND}]
    volumes: [${CONTECO_DC_OVERLAY_METRICS_VOLUMES}]
    ports: [${CONTECO_DC_OVERLAY_METRICS_PORTS}]
    networks: [${CONTECO_DC_OVERLAY_METRICS_NETWORKS}]
    deploy:
      mode: ${CONTECO_DC_OVERLAY_METRICS_DEPLOY_MODE}
      resources:
        limits:
          cpus: '${CONTECO_DC_OVERLAY_METRICS_DEPLOY_RESOURCES_LIMITS_CPUS}'
          memory: '${CONTECO_DC_OVERLAY_METRICS_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          cpus: '${CONTECO_DC_OVERLAY_METRICS_DEPLOY_RESOURCES_RESERVATIONS_CPUS}'
          memory: '${CONTECO_DC_OVERLAY_METRICS_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
      labels: [${CONTECO_DC_OVERLAY_METRICS_DEPLOY_LABELS}]
# END SERVICE metricbeat.overlay

volumes: {${CONTECO_DC_GLOBAL_VOLUMES}}
networks: {${CONTECO_TYPE}_overlay: { external: true }}
